SELECT 
    id,
    admission_no,
    registration_no,
    origin,
    gender,
    branch_id,
    batch_year,
    year_of_join,
    type_of_join,
    year_of_exit,
    type_of_exit,
    social_disadvantage,
    economic_disadvantage,
    physically_challenged
FROM 
    students;
